import type { FitQuestion, Mission, ProgressEvent } from './types'

export const missions: Mission[] = [
  {
    id: 'neighbor',
    slug: 'neighbor',
    company: 'Neighbor',
    headline: 'Turn every empty space into useful storage.',
    mission: 'Give people affordable storage by unlocking the unused space already around them.',
    founderStory: 'The idea started when a student needed storage, couldn’t find a good option, and saw unused basements everywhere.',
    longDescription: 'Neighbor builds a peer-to-peer storage marketplace that makes existing real estate more useful and gives hosts a new income stream.',
    location: 'Lehi, Utah',
    website: 'https://www.neighbor.com',
    themes: ['marketplaces', 'consumer', 'real estate', 'logistics', 'trust'],
    accent: '#c8ff4d',
    imageUrl: 'https://images.unsplash.com/photo-1570086625846-f33f679eb4f5?auto=format&fit=crop&w=1600&q=85',
    roleArchetypes: ['Marketplace Product Engineer', 'Trust & Safety Data Analyst', 'Growth Product Manager'],
    projectSeeds: ['marketplace liquidity', 'trust scoring', 'space utilization'],
  },
  {
    id: 'redo',
    slug: 'redo',
    company: 'Redo',
    headline: 'Make every return feel as good as the purchase.',
    mission: 'Turn ecommerce returns from a cost center into a customer-retention engine.',
    founderStory: 'Built by ecommerce operators who watched returns erode margins and customer trust—and decided the workflow deserved a reset.',
    longDescription: 'Redo helps merchants offer flexible return coverage while automating the operational decisions behind returns and exchanges.',
    location: 'Draper, Utah',
    website: 'https://www.getredo.com',
    themes: ['ecommerce', 'fintech', 'operations', 'customer experience', 'automation'],
    accent: '#ff7657',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1600&q=85',
    roleArchetypes: ['Commerce Platform Engineer', 'Merchant Data Analyst', 'Lifecycle Product Designer'],
    projectSeeds: ['return prediction', 'merchant analytics', 'exchange optimization'],
  },
  {
    id: 'waystar',
    slug: 'waystar',
    company: 'Waystar',
    headline: 'Take the friction out of getting healthcare paid for.',
    mission: 'Simplify healthcare payments so providers can focus more energy on patient care.',
    founderStory: 'A Utah-born healthcare technology story shaped by the belief that billing complexity should not stand between care and payment.',
    longDescription: 'Waystar connects the healthcare revenue cycle with software that helps providers manage claims, payments, and financial experiences.',
    location: 'Lehi, Utah',
    website: 'https://www.waystar.com',
    themes: ['healthtech', 'payments', 'data', 'enterprise software', 'automation'],
    accent: '#74d6ff',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1600&q=85',
    roleArchetypes: ['Healthcare Data Engineer', 'Revenue Cycle Product Analyst', 'Applied AI Engineer'],
    projectSeeds: ['claims intelligence', 'payment transparency', 'denial prevention'],
  },
  {
    id: 'weave',
    slug: 'weave',
    company: 'Weave',
    headline: 'Make the small healthcare practice feel brilliantly connected.',
    mission: 'Help local healthcare businesses communicate, collect, and grow through one connected platform.',
    founderStory: 'Started in Utah after seeing how often dental practices lost time and relationships to disconnected front-office tools.',
    longDescription: 'Weave combines patient communications, scheduling, payments, and operational tools for small healthcare practices.',
    location: 'Lehi, Utah',
    website: 'https://www.getweave.com',
    themes: ['healthtech', 'communications', 'small business', 'payments', 'product'],
    accent: '#d7b7ff',
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1600&q=85',
    roleArchetypes: ['Full-stack Product Engineer', 'Customer Insights Analyst', 'Product Designer'],
    projectSeeds: ['patient communication', 'practice operations', 'appointment retention'],
  },
  {
    id: 'podium',
    slug: 'podium',
    company: 'Podium',
    headline: 'Help every local business win the next customer.',
    mission: 'Give local businesses the communication and AI tools once reserved for massive companies.',
    founderStory: 'Founded in Utah after seeing a tire shop with great service lose business because its online reputation told the wrong story.',
    longDescription: 'Podium brings messaging, reviews, payments, and AI-powered lead conversion into one operating layer for local businesses.',
    location: 'Lehi, Utah',
    website: 'https://www.podium.com',
    themes: ['AI', 'local business', 'communications', 'payments', 'growth'],
    accent: '#ffe060',
    imageUrl: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1600&q=85',
    roleArchetypes: ['AI Product Engineer', 'Growth Data Scientist', 'Conversation Designer'],
    projectSeeds: ['lead conversion', 'reputation intelligence', 'AI messaging'],
  },
]

export const fitQuestions: FitQuestion[] = [
  {
    id: 'work',
    eyebrow: '01 / The work',
    question: 'What kind of hard problem would you happily keep thinking about?',
    options: ['Building products people touch daily', 'Finding signal in messy data', 'Designing systems that scale', 'Understanding people and behavior'],
  },
  {
    id: 'impact',
    eyebrow: '02 / The impact',
    question: 'Which result would make a Friday feel well spent?',
    options: ['A customer saved real time or money', 'A broken process became effortless', 'A team made a smarter decision', 'A new idea became tangible'],
  },
  {
    id: 'edge',
    eyebrow: '03 / Your edge',
    question: 'What do people already trust you to do?',
    options: ['Ship and iterate quickly', 'Explain complex things clearly', 'Spot patterns others miss', 'Bring people around an idea'],
  },
]

export const initialProgress: ProgressEvent[] = [
  {
    id: 'welcome',
    type: 'project_milestone',
    label: 'Chose a mission worth pursuing',
    points: 20,
    verified: true,
    occurredAt: new Date().toISOString(),
  },
]
