import type { CompanyIntel, Mission, ProgressEvent } from './types'

export const missions: Mission[] = [
  { id: 'neighbor', company: 'Neighbor', domain: 'neighbor.com', mission: 'Unlock the world’s unused space so storage is closer, more affordable, and more human.', founderStory: 'A student needed storage, saw empty basements everywhere, and turned that mismatch into a marketplace.', themes: ['marketplaces', 'real estate', 'trust'], accent: '#2775ff', logoUrl: '/logos/neighbor.png', roleArchetypes: ['Marketplace Product Engineer', 'Trust & Safety Data Analyst', 'Growth Product Manager'], projectSeeds: ['marketplace liquidity', 'trust scoring', 'space utilization'], locations: ['Utah', 'Lehi'] },
  { id: 'redo', company: 'Redo', domain: 'getredo.com', mission: 'Make every ecommerce return feel as considered as the original purchase.', founderStory: 'Ecommerce operators watched returns erode margins and loyalty, then rebuilt the experience around retention.', themes: ['ecommerce', 'operations', 'customer experience'], accent: '#ff6d3d', logoUrl: '/logos/redo.png', roleArchetypes: ['Commerce Platform Engineer', 'Merchant Data Analyst', 'Lifecycle Product Designer'], projectSeeds: ['return prediction', 'merchant analytics', 'exchange optimization'], locations: ['Utah', 'Draper'] },
  { id: 'waystar', company: 'Waystar', domain: 'waystar.com', mission: 'Simplify healthcare payments so providers can focus more energy on patient care.', founderStory: 'The platform grew from a belief that billing complexity should not stand between care and payment.', themes: ['healthtech', 'payments', 'enterprise software'], accent: '#ff7426', logoUrl: '/logos/waystar.png', roleArchetypes: ['Healthcare Data Engineer', 'Revenue Cycle Product Analyst', 'Applied AI Engineer'], projectSeeds: ['claims intelligence', 'payment transparency', 'denial prevention'], locations: ['Utah', 'Lehi', 'Louisville'] },
  { id: 'google', company: 'Google', domain: 'google.com', mission: 'Organize the world’s information and make it universally accessible and useful.', founderStory: 'A research project about ranking the web became infrastructure for how billions of people find knowledge.', themes: ['information', 'AI', 'infrastructure'], accent: '#4285f4', logoUrl: '/logos/google.png', roleArchetypes: ['Software Engineer', 'Machine Learning Engineer', 'Product Manager'], projectSeeds: ['information retrieval', 'responsible AI', 'developer productivity'] },
  { id: 'apple', company: 'Apple', domain: 'apple.com', mission: 'Build products where technology, design, and the liberal arts make each other more powerful.', founderStory: 'A personal-computing revolution became a decades-long pursuit of tools that feel deeply human.', themes: ['consumer hardware', 'design', 'privacy'], accent: '#111111', logoUrl: '/logos/apple.png', roleArchetypes: ['Software Engineer', 'Product Designer', 'Hardware Systems Engineer'], projectSeeds: ['human-computer interaction', 'privacy by design', 'device intelligence'] },
  { id: 'meta', company: 'Meta', domain: 'meta.com', mission: 'Build technology that helps people connect, find communities, and grow businesses.', founderStory: 'A college directory evolved into a global social layer—and now a bet on more embodied computing.', themes: ['social products', 'AI', 'mixed reality'], accent: '#0866ff', logoUrl: '/logos/meta.png', roleArchetypes: ['Product Engineer', 'Machine Learning Engineer', 'Product Designer'], projectSeeds: ['healthy communities', 'recommendation systems', 'spatial interaction'] },
  { id: 'amazon', company: 'Amazon', domain: 'amazon.com', mission: 'Make it possible for customers to find, discover, and buy anything with exceptional convenience.', founderStory: 'An online bookstore became a system for relentless customer obsession at enormous scale.', themes: ['commerce', 'cloud', 'logistics'], accent: '#ff9900', logoUrl: '/logos/amazon.png', roleArchetypes: ['Software Development Engineer', 'Operations Research Scientist', 'Product Manager'], projectSeeds: ['delivery optimization', 'seller tools', 'cloud reliability'], locations: ['Seattle', 'Global'] },
  { id: 'netflix', company: 'Netflix', domain: 'netflix.com', mission: 'Entertain the world with stories people love, wherever they are.', founderStory: 'DVDs by mail became a global streaming and storytelling platform built on product experimentation.', themes: ['entertainment', 'personalization', 'streaming'], accent: '#e50914', logoUrl: '/logos/netflix.png', roleArchetypes: ['Streaming Platform Engineer', 'Machine Learning Scientist', 'Product Designer'], projectSeeds: ['content discovery', 'streaming quality', 'creative tooling'] },
  { id: 'microsoft', company: 'Microsoft', domain: 'microsoft.com', mission: 'Empower every person and every organization on the planet to achieve more.', founderStory: 'A software company for the personal-computer era became a platform spanning cloud, productivity, gaming, and AI.', themes: ['productivity', 'cloud', 'AI'], accent: '#00a4ef', logoUrl: '/logos/microsoft.png', roleArchetypes: ['Software Engineer', 'Cloud Solutions Architect', 'Product Manager'], projectSeeds: ['knowledge work', 'cloud efficiency', 'accessible AI'], locations: ['Seattle', 'Redmond', 'Global'] },
  { id: 'openai', company: 'OpenAI', domain: 'openai.com', mission: 'Ensure that artificial general intelligence benefits all of humanity.', founderStory: 'An AI research lab became a product company focused on making increasingly capable systems useful and broadly beneficial.', themes: ['AI', 'alignment', 'developer tools'], accent: '#10a37f', logoUrl: '/logos/openai.png', roleArchetypes: ['Research Engineer', 'Applied AI Engineer', 'Product Manager'], projectSeeds: ['model evaluation', 'agent reliability', 'human feedback'] },
  { id: 'anthropic', company: 'Anthropic', domain: 'anthropic.com', mission: 'Build reliable, interpretable, and steerable AI systems that people can trust.', founderStory: 'Researchers focused on AI safety built a company around useful systems with rigorous safeguards.', themes: ['AI safety', 'interpretability', 'agents'], accent: '#d97757', logoUrl: '/logos/anthropic.png', roleArchetypes: ['Research Engineer', 'Machine Learning Systems Engineer', 'Product Engineer'], projectSeeds: ['model interpretability', 'agent safety', 'evaluation systems'] },
  { id: 'nvidia', company: 'NVIDIA', domain: 'nvidia.com', mission: 'Solve computing problems that ordinary computers cannot.', founderStory: 'A graphics-chip company became the computing platform behind modern AI and accelerated science.', themes: ['accelerated computing', 'AI', 'simulation'], accent: '#76b900', logoUrl: '/logos/nvidia.png', roleArchetypes: ['Systems Software Engineer', 'Deep Learning Engineer', 'Developer Relations Engineer'], projectSeeds: ['inference efficiency', 'parallel computing', 'simulation tooling'] },
  { id: 'stripe', company: 'Stripe', domain: 'stripe.com', mission: 'Increase the GDP of the internet.', founderStory: 'Two brothers made online payments dramatically easier for developers, then expanded into financial infrastructure.', themes: ['fintech', 'developer experience', 'internet economy'], accent: '#635bff', logoUrl: '/logos/stripe.png', roleArchetypes: ['Product Engineer', 'Infrastructure Engineer', 'Product Designer'], projectSeeds: ['payment reliability', 'developer onboarding', 'fraud prevention'] },
  { id: 'airbnb', company: 'Airbnb', domain: 'airbnb.com', mission: 'Create a world where anyone can belong anywhere.', founderStory: 'Three hosts with an air mattress reframed spare space as a doorway into local belonging.', themes: ['travel', 'marketplaces', 'trust'], accent: '#ff385c', logoUrl: '/logos/airbnb.png', roleArchetypes: ['Marketplace Engineer', 'Trust Data Scientist', 'Experience Designer'], projectSeeds: ['marketplace trust', 'trip planning', 'host success'] },
  { id: 'tesla', company: 'Tesla', domain: 'tesla.com', mission: 'Accelerate the world’s transition to sustainable energy.', founderStory: 'An electric sports car became a proving ground for rethinking vehicles, energy, and manufacturing.', themes: ['climate', 'robotics', 'manufacturing'], accent: '#e82127', logoUrl: '/logos/tesla.png', roleArchetypes: ['Embedded Software Engineer', 'Robotics Engineer', 'Manufacturing Data Analyst'], projectSeeds: ['energy optimization', 'robot perception', 'manufacturing quality'] },
  { id: 'spacex', company: 'SpaceX', domain: 'spacex.com', mission: 'Make humanity multiplanetary by radically reducing the cost of access to space.', founderStory: 'A startup treated rockets as reusable systems and changed the economics of orbital launch.', themes: ['space', 'aerospace', 'manufacturing'], accent: '#1c2b39', logoUrl: '/logos/spacex.png', roleArchetypes: ['Flight Software Engineer', 'Aerospace Engineer', 'Manufacturing Engineer'], projectSeeds: ['mission simulation', 'telemetry reliability', 'manufacturing throughput'] },
  { id: 'qualtrics', company: 'Qualtrics', domain: 'qualtrics.com', mission: 'Build technology that closes the gap between what people expect and what organizations deliver.', founderStory: 'Brothers Ryan and Jared Smith began with survey software in a Utah basement and grew it around understanding human experience.', themes: ['AI', 'analytics', 'customer experience', 'enterprise software'], accent: '#6d5dfc', logoUrl: 'https://www.google.com/s2/favicons?domain=qualtrics.com&sz=128', roleArchetypes: ['Software Engineer', 'Data Scientist', 'Product Manager'], projectSeeds: ['experience intelligence', 'survey insight', 'customer prediction'], locations: ['Utah', 'Provo', 'Seattle'] },
  { id: 'lucid', company: 'Lucid Software', domain: 'lucid.co', mission: 'Help teams see and build the future faster.', founderStory: 'Karl Sun and Ben Dilts saw that visual collaboration belonged in the cloud and built a shared workspace before it was obvious.', themes: ['productivity', 'design', 'collaboration', 'AI'], accent: '#f59e0b', logoUrl: 'https://www.google.com/s2/favicons?domain=lucid.co&sz=128', roleArchetypes: ['Product Engineer', 'Product Designer', 'AI Engineer'], projectSeeds: ['visual collaboration', 'diagram intelligence', 'team alignment'], locations: ['Utah', 'South Jordan'] },
  { id: 'podium', company: 'Podium', domain: 'podium.com', mission: 'Help local businesses win by turning every interaction into an opportunity.', founderStory: 'Eric Rea watched his father’s tire shop struggle online and built a product to help local businesses compete.', themes: ['local business', 'AI', 'communications', 'commerce'], accent: '#5a4bff', logoUrl: 'https://www.google.com/s2/favicons?domain=podium.com&sz=128', roleArchetypes: ['Product Engineer', 'Applied AI Engineer', 'Growth Product Manager'], projectSeeds: ['customer messaging', 'local business automation', 'lead conversion'], locations: ['Utah', 'Lehi'] },
  { id: 'domo', company: 'Domo', domain: 'domo.com', mission: 'Put data to work for everyone so they can multiply their impact.', founderStory: 'Josh James built Domo after seeing leaders struggle to get timely answers from fragmented business data.', themes: ['data', 'analytics', 'AI', 'enterprise software'], accent: '#2e75b6', logoUrl: 'https://www.google.com/s2/favicons?domain=domo.com&sz=128', roleArchetypes: ['Data Engineer', 'Analytics Engineer', 'Product Manager'], projectSeeds: ['decision intelligence', 'data accessibility', 'business dashboards'], locations: ['Utah', 'American Fork'] },
  { id: 'pluralsight', company: 'Pluralsight', domain: 'pluralsight.com', mission: 'Advance the world’s technology workforce.', founderStory: 'Aaron Skonnard and his cofounders turned in-person technical training into a platform for continuous technology learning.', themes: ['education', 'developer tools', 'skills', 'AI'], accent: '#f15b2a', logoUrl: 'https://www.google.com/s2/favicons?domain=pluralsight.com&sz=128', roleArchetypes: ['Software Engineer', 'Learning Product Manager', 'Data Scientist'], projectSeeds: ['adaptive learning', 'skill assessment', 'developer education'], locations: ['Utah', 'Draper'] },
  { id: 'entrata', company: 'Entrata', domain: 'entrata.com', mission: 'Make property management simpler for everyone who lives and works in a community.', founderStory: 'Dave Bateman began by replacing disconnected apartment software with one unified operating system.', themes: ['real estate', 'fintech', 'enterprise software', 'operations'], accent: '#f05a28', logoUrl: 'https://www.google.com/s2/favicons?domain=entrata.com&sz=128', roleArchetypes: ['Software Engineer', 'Fintech Product Manager', 'Data Analyst'], projectSeeds: ['resident experience', 'property operations', 'payment automation'], locations: ['Utah', 'Lehi'] },
  { id: 'weave', company: 'Weave', domain: 'getweave.com', mission: 'Connect the entire patient journey so healthcare practices can focus on care.', founderStory: 'The founders saw small healthcare practices juggling disconnected phones and software and built one communication platform.', themes: ['healthcare', 'communications', 'payments', 'small business'], accent: '#14b8a6', logoUrl: 'https://www.google.com/s2/favicons?domain=getweave.com&sz=128', roleArchetypes: ['Product Engineer', 'Healthcare Product Manager', 'UX Designer'], projectSeeds: ['patient communication', 'practice workflow', 'payment experience'], locations: ['Utah', 'Lehi'] },
  { id: 'recursion', company: 'Recursion', domain: 'recursion.com', mission: 'Decode biology to radically improve lives by industrializing drug discovery.', founderStory: 'Physician-scientists and technologists combined automated biology with machine learning to search for medicines differently.', themes: ['biotech', 'AI', 'healthcare', 'scientific computing'], accent: '#3454d1', logoUrl: 'https://www.google.com/s2/favicons?domain=recursion.com&sz=128', roleArchetypes: ['Machine Learning Engineer', 'Computational Biologist', 'Data Engineer'], projectSeeds: ['biological data', 'drug discovery models', 'lab automation'], locations: ['Utah', 'Salt Lake City', 'Boston'] },
  { id: 'owlet', company: 'Owlet', domain: 'owletcare.com', mission: 'Give parents better data and peace of mind through connected infant health technology.', founderStory: 'A team of parents and engineers set out to make hospital-grade signals useful at home.', themes: ['healthcare', 'consumer hardware', 'data', 'family'], accent: '#45a9b8', logoUrl: 'https://www.google.com/s2/favicons?domain=owletcare.com&sz=128', roleArchetypes: ['Mobile Engineer', 'Data Scientist', 'Hardware Product Manager'], projectSeeds: ['infant health signals', 'caregiver alerts', 'connected devices'], locations: ['Utah', 'Lehi'] },
  { id: 'pattern', company: 'Pattern', domain: 'pattern.com', mission: 'Accelerate brands on global ecommerce marketplaces with data and technology.', founderStory: 'David Wright and Melanie Alder began by helping brands solve the operating complexity of selling online at global scale.', themes: ['ecommerce', 'AI', 'analytics', 'marketplaces'], accent: '#111827', logoUrl: 'https://www.google.com/s2/favicons?domain=pattern.com&sz=128', roleArchetypes: ['Commerce Data Scientist', 'Software Engineer', 'Marketplace Product Manager'], projectSeeds: ['marketplace growth', 'demand forecasting', 'brand analytics'], locations: ['Utah', 'Lehi'] },
  { id: 'route', company: 'Route', domain: 'route.com', mission: 'Make the post-purchase experience simpler, safer, and more connected.', founderStory: 'Route began with the belief that a purchase should not become invisible after checkout.', themes: ['ecommerce', 'logistics', 'consumer experience', 'fintech'], accent: '#5b5cf0', logoUrl: 'https://www.google.com/s2/favicons?domain=route.com&sz=128', roleArchetypes: ['Product Engineer', 'Logistics Data Analyst', 'Product Designer'], projectSeeds: ['package visibility', 'delivery protection', 'post-purchase loyalty'], locations: ['Utah', 'Lehi'] },
  { id: 'adobe', company: 'Adobe', domain: 'adobe.com', mission: 'Change the world through personalized digital experiences.', founderStory: 'John Warnock and Charles Geschke founded Adobe to make digital documents and creative expression work across computers.', themes: ['design', 'creativity', 'AI', 'enterprise software'], accent: '#e11d48', logoUrl: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=128', roleArchetypes: ['Software Engineer', 'Product Designer', 'Machine Learning Engineer'], projectSeeds: ['creative intelligence', 'document workflows', 'digital experiences'], locations: ['Utah', 'Lehi', 'Bay Area'] },
  { id: 'ancestry', company: 'Ancestry', domain: 'ancestry.com', mission: 'Empower journeys of personal discovery to enrich lives.', founderStory: 'A Utah publishing project grew into a platform connecting historical records, family stories, and genetics.', themes: ['consumer data', 'history', 'biotech', 'family'], accent: '#70a63b', logoUrl: 'https://www.google.com/s2/favicons?domain=ancestry.com&sz=128', roleArchetypes: ['Data Engineer', 'Bioinformatics Scientist', 'Product Manager'], projectSeeds: ['record discovery', 'family graph', 'genetic insight'], locations: ['Utah', 'Lehi'] },
  { id: 'figma', company: 'Figma', domain: 'figma.com', mission: 'Make design accessible to everyone.', founderStory: 'Dylan Field and Evan Wallace bet that professional design tools could live in the browser and become multiplayer.', themes: ['design', 'collaboration', 'developer tools', 'AI'], accent: '#a259ff', logoUrl: 'https://www.google.com/s2/favicons?domain=figma.com&sz=128', roleArchetypes: ['Product Engineer', 'Product Designer', 'Developer Advocate'], projectSeeds: ['multiplayer creativity', 'design systems', 'developer handoff'], locations: ['Bay Area', 'New York', 'Global'] },
  { id: 'duolingo', company: 'Duolingo', domain: 'duolingo.com', mission: 'Develop the best education in the world and make it universally available.', founderStory: 'Luis von Ahn and Severin Hacker paired free language education with game mechanics that keep people practicing.', themes: ['education', 'AI', 'consumer product', 'games'], accent: '#58cc02', logoUrl: 'https://www.google.com/s2/favicons?domain=duolingo.com&sz=128', roleArchetypes: ['Product Engineer', 'Learning Scientist', 'Product Designer'], projectSeeds: ['learning retention', 'adaptive practice', 'motivation systems'], locations: ['Pittsburgh', 'Seattle', 'New York'] },
  { id: 'cloudflare', company: 'Cloudflare', domain: 'cloudflare.com', mission: 'Help build a better internet.', founderStory: 'Matthew Prince, Michelle Zatlyn, and Lee Holloway turned a project about tracking web abuse into protective infrastructure for the internet.', themes: ['cybersecurity', 'infrastructure', 'developer tools', 'AI'], accent: '#f48120', logoUrl: 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=128', roleArchetypes: ['Systems Engineer', 'Security Engineer', 'Developer Platform Product Manager'], projectSeeds: ['internet resilience', 'edge computing', 'abuse prevention'], locations: ['Bay Area', 'Seattle', 'Global'] },
  { id: 'moderna', company: 'Moderna', domain: 'modernatx.com', mission: 'Deliver the greatest possible impact to people through mRNA medicines.', founderStory: 'Scientists and investors formed Moderna around the idea that messenger RNA could become a programmable medicine platform.', themes: ['biotech', 'healthcare', 'data', 'research'], accent: '#e11d48', logoUrl: 'https://www.google.com/s2/favicons?domain=modernatx.com&sz=128', roleArchetypes: ['Computational Scientist', 'Data Engineer', 'Clinical Product Manager'], projectSeeds: ['mRNA design', 'clinical evidence', 'manufacturing intelligence'], locations: ['Boston', 'Global'] },
]

export const initialProgress: ProgressEvent[] = [
  { id: 'mission', type: 'project_milestone', label: 'Chose a north star', points: 20, verified: true, occurredAt: new Date().toISOString() },
]

export const fallbackIntel: CompanyIntel = { people: [], jobs: [], events: [], feed: [], researchedAt: new Date().toISOString(), live: false }
