import type { CompanyIntel, Mission, ProgressEvent } from './types'

export const missions: Mission[] = [
  { id: 'neighbor', company: 'Neighbor', domain: 'neighbor.com', mission: 'Unlock the world’s unused space so storage is closer, more affordable, and more human.', founderStory: 'A student needed storage, saw empty basements everywhere, and turned that mismatch into a marketplace.', themes: ['marketplaces', 'real estate', 'trust'], accent: '#2775ff', logoUrl: '/logos/neighbor.png', roleArchetypes: ['Marketplace Product Engineer', 'Trust & Safety Data Analyst', 'Growth Product Manager'], projectSeeds: ['marketplace liquidity', 'trust scoring', 'space utilization'] },
  { id: 'redo', company: 'Redo', domain: 'getredo.com', mission: 'Make every ecommerce return feel as considered as the original purchase.', founderStory: 'Ecommerce operators watched returns erode margins and loyalty, then rebuilt the experience around retention.', themes: ['ecommerce', 'operations', 'customer experience'], accent: '#ff6d3d', logoUrl: '/logos/redo.png', roleArchetypes: ['Commerce Platform Engineer', 'Merchant Data Analyst', 'Lifecycle Product Designer'], projectSeeds: ['return prediction', 'merchant analytics', 'exchange optimization'] },
  { id: 'waystar', company: 'Waystar', domain: 'waystar.com', mission: 'Simplify healthcare payments so providers can focus more energy on patient care.', founderStory: 'The platform grew from a belief that billing complexity should not stand between care and payment.', themes: ['healthtech', 'payments', 'enterprise software'], accent: '#ff7426', logoUrl: '/logos/waystar.png', roleArchetypes: ['Healthcare Data Engineer', 'Revenue Cycle Product Analyst', 'Applied AI Engineer'], projectSeeds: ['claims intelligence', 'payment transparency', 'denial prevention'] },
  { id: 'google', company: 'Google', domain: 'google.com', mission: 'Organize the world’s information and make it universally accessible and useful.', founderStory: 'A research project about ranking the web became infrastructure for how billions of people find knowledge.', themes: ['information', 'AI', 'infrastructure'], accent: '#4285f4', logoUrl: '/logos/google.png', roleArchetypes: ['Software Engineer', 'Machine Learning Engineer', 'Product Manager'], projectSeeds: ['information retrieval', 'responsible AI', 'developer productivity'] },
  { id: 'apple', company: 'Apple', domain: 'apple.com', mission: 'Build products where technology, design, and the liberal arts make each other more powerful.', founderStory: 'A personal-computing revolution became a decades-long pursuit of tools that feel deeply human.', themes: ['consumer hardware', 'design', 'privacy'], accent: '#111111', logoUrl: '/logos/apple.png', roleArchetypes: ['Software Engineer', 'Product Designer', 'Hardware Systems Engineer'], projectSeeds: ['human-computer interaction', 'privacy by design', 'device intelligence'] },
  { id: 'meta', company: 'Meta', domain: 'meta.com', mission: 'Build technology that helps people connect, find communities, and grow businesses.', founderStory: 'A college directory evolved into a global social layer—and now a bet on more embodied computing.', themes: ['social products', 'AI', 'mixed reality'], accent: '#0866ff', logoUrl: '/logos/meta.png', roleArchetypes: ['Product Engineer', 'Machine Learning Engineer', 'Product Designer'], projectSeeds: ['healthy communities', 'recommendation systems', 'spatial interaction'] },
  { id: 'amazon', company: 'Amazon', domain: 'amazon.com', mission: 'Make it possible for customers to find, discover, and buy anything with exceptional convenience.', founderStory: 'An online bookstore became a system for relentless customer obsession at enormous scale.', themes: ['commerce', 'cloud', 'logistics'], accent: '#ff9900', logoUrl: '/logos/amazon.png', roleArchetypes: ['Software Development Engineer', 'Operations Research Scientist', 'Product Manager'], projectSeeds: ['delivery optimization', 'seller tools', 'cloud reliability'] },
  { id: 'netflix', company: 'Netflix', domain: 'netflix.com', mission: 'Entertain the world with stories people love, wherever they are.', founderStory: 'DVDs by mail became a global streaming and storytelling platform built on product experimentation.', themes: ['entertainment', 'personalization', 'streaming'], accent: '#e50914', logoUrl: '/logos/netflix.png', roleArchetypes: ['Streaming Platform Engineer', 'Machine Learning Scientist', 'Product Designer'], projectSeeds: ['content discovery', 'streaming quality', 'creative tooling'] },
  { id: 'microsoft', company: 'Microsoft', domain: 'microsoft.com', mission: 'Empower every person and every organization on the planet to achieve more.', founderStory: 'A software company for the personal-computer era became a platform spanning cloud, productivity, gaming, and AI.', themes: ['productivity', 'cloud', 'AI'], accent: '#00a4ef', logoUrl: '/logos/microsoft.png', roleArchetypes: ['Software Engineer', 'Cloud Solutions Architect', 'Product Manager'], projectSeeds: ['knowledge work', 'cloud efficiency', 'accessible AI'] },
  { id: 'openai', company: 'OpenAI', domain: 'openai.com', mission: 'Ensure that artificial general intelligence benefits all of humanity.', founderStory: 'An AI research lab became a product company focused on making increasingly capable systems useful and broadly beneficial.', themes: ['AI', 'alignment', 'developer tools'], accent: '#10a37f', logoUrl: '/logos/openai.png', roleArchetypes: ['Research Engineer', 'Applied AI Engineer', 'Product Manager'], projectSeeds: ['model evaluation', 'agent reliability', 'human feedback'] },
  { id: 'anthropic', company: 'Anthropic', domain: 'anthropic.com', mission: 'Build reliable, interpretable, and steerable AI systems that people can trust.', founderStory: 'Researchers focused on AI safety built a company around useful systems with rigorous safeguards.', themes: ['AI safety', 'interpretability', 'agents'], accent: '#d97757', logoUrl: '/logos/anthropic.png', roleArchetypes: ['Research Engineer', 'Machine Learning Systems Engineer', 'Product Engineer'], projectSeeds: ['model interpretability', 'agent safety', 'evaluation systems'] },
  { id: 'nvidia', company: 'NVIDIA', domain: 'nvidia.com', mission: 'Solve computing problems that ordinary computers cannot.', founderStory: 'A graphics-chip company became the computing platform behind modern AI and accelerated science.', themes: ['accelerated computing', 'AI', 'simulation'], accent: '#76b900', logoUrl: '/logos/nvidia.png', roleArchetypes: ['Systems Software Engineer', 'Deep Learning Engineer', 'Developer Relations Engineer'], projectSeeds: ['inference efficiency', 'parallel computing', 'simulation tooling'] },
  { id: 'stripe', company: 'Stripe', domain: 'stripe.com', mission: 'Increase the GDP of the internet.', founderStory: 'Two brothers made online payments dramatically easier for developers, then expanded into financial infrastructure.', themes: ['fintech', 'developer experience', 'internet economy'], accent: '#635bff', logoUrl: '/logos/stripe.png', roleArchetypes: ['Product Engineer', 'Infrastructure Engineer', 'Product Designer'], projectSeeds: ['payment reliability', 'developer onboarding', 'fraud prevention'] },
  { id: 'airbnb', company: 'Airbnb', domain: 'airbnb.com', mission: 'Create a world where anyone can belong anywhere.', founderStory: 'Three hosts with an air mattress reframed spare space as a doorway into local belonging.', themes: ['travel', 'marketplaces', 'trust'], accent: '#ff385c', logoUrl: '/logos/airbnb.png', roleArchetypes: ['Marketplace Engineer', 'Trust Data Scientist', 'Experience Designer'], projectSeeds: ['marketplace trust', 'trip planning', 'host success'] },
  { id: 'tesla', company: 'Tesla', domain: 'tesla.com', mission: 'Accelerate the world’s transition to sustainable energy.', founderStory: 'An electric sports car became a proving ground for rethinking vehicles, energy, and manufacturing.', themes: ['climate', 'robotics', 'manufacturing'], accent: '#e82127', logoUrl: '/logos/tesla.png', roleArchetypes: ['Embedded Software Engineer', 'Robotics Engineer', 'Manufacturing Data Analyst'], projectSeeds: ['energy optimization', 'robot perception', 'manufacturing quality'] },
  { id: 'spacex', company: 'SpaceX', domain: 'spacex.com', mission: 'Make humanity multiplanetary by radically reducing the cost of access to space.', founderStory: 'A startup treated rockets as reusable systems and changed the economics of orbital launch.', themes: ['space', 'aerospace', 'manufacturing'], accent: '#1c2b39', logoUrl: '/logos/spacex.png', roleArchetypes: ['Flight Software Engineer', 'Aerospace Engineer', 'Manufacturing Engineer'], projectSeeds: ['mission simulation', 'telemetry reliability', 'manufacturing throughput'] },
]

export const initialProgress: ProgressEvent[] = [
  { id: 'mission', type: 'project_milestone', label: 'Chose a north star', points: 20, verified: true, occurredAt: new Date().toISOString() },
]

export const fallbackIntel: CompanyIntel = { people: [], jobs: [], events: [], feed: [], researchedAt: new Date().toISOString(), live: false }
