import type { LearningResource, Mission, PathStep, ResumeIntake, StudentProfile } from './types'

const resourcesFor = (role: string, mission: Mission) => {
  const context = `${role} ${mission.themes.join(' ')}`
  if (/health|claim|data engineer|analyst/i.test(context)) return [
    { title: 'CMS Blue Button 2.0 API documentation', provider: 'Centers for Medicare & Medicaid Services', url: 'https://bluebutton.cms.gov/developers/', skill: 'Healthcare data', kind: 'reading' as const },
    { title: 'PostgreSQL tutorial: window functions', provider: 'PostgreSQL', url: 'https://www.postgresql.org/docs/current/tutorial-window.html', skill: 'SQL', kind: 'reading' as const },
    { title: 'Pandas group by: split-apply-combine', provider: 'pandas', url: 'https://pandas.pydata.org/docs/user_guide/groupby.html', skill: 'Python', kind: 'reading' as const },
  ]
  if (/robot|autonom|perception/i.test(context)) return [
    { title: 'ROS 2 Tutorials', provider: 'Open Robotics', url: 'https://docs.ros.org/en/jazzy/Tutorials.html', skill: 'ROS 2', kind: 'reading' as const },
    { title: 'A* Search Algorithm', provider: 'Red Blob Games', url: 'https://www.redblobgames.com/pathfinding/a-star/introduction.html', skill: 'Path planning', kind: 'reading' as const },
    { title: 'Kalman Filter in one dimension', provider: 'KalmanFilter.net', url: 'https://www.kalmanfilter.net/kalman1d.html', skill: 'Sensor fusion', kind: 'reading' as const },
  ]
  if (/flight|space|aerospace|embedded/i.test(context)) return [
    { title: 'Core Flight System documentation', provider: 'NASA', url: 'https://cfs-documents.github.io/', skill: 'Flight software', kind: 'reading' as const },
    { title: 'Protocol Buffers overview', provider: 'Google for Developers', url: 'https://protobuf.dev/overview/', skill: 'Telemetry schemas', kind: 'reading' as const },
    { title: 'State Machine Design in C', provider: 'Barr Group', url: 'https://barrgroup.com/blog/how-code-state-machine-c-or-c', skill: 'State machines', kind: 'reading' as const },
  ]
  return [
    { title: 'GitHub Actions quickstart', provider: 'GitHub Docs', url: 'https://docs.github.com/en/actions/writing-workflows/quickstart', skill: 'CI', kind: 'reading' as const },
    { title: 'Docker workshop', provider: 'Docker Docs', url: 'https://docs.docker.com/get-started/workshop/', skill: 'Containers', kind: 'reading' as const },
    { title: 'SQL joins', provider: 'SQLBolt', url: 'https://sqlbolt.com/lesson/select_queries_with_joins', skill: 'SQL', kind: 'exercise' as const },
  ]
}

export function buildJobGroundedPath(profile: StudentProfile, intake: ResumeIntake, mission: Mission, role: string, personalization?: { why?: string; motivation?: string }): PathStep[] {
  if (mission.id === 'neighbor') return buildNeighborPath(profile, intake, mission, role, personalization)
  const resources = resourcesFor(role, mission)
  const actualSkills = intake.skills.filter((skill) => !/computer science|^cs$|major/i.test(skill))
  const lead = actualSkills[0] ?? (/data|analyst/i.test(role) ? 'Python and SQL' : 'software engineering')
  const context = `${role} ${mission.themes.join(' ')}`
  const names = /health|claim|data engineer|analyst/i.test(context)
    ? ['Claims Quality Pipeline', 'Denial Intelligence System', 'Revenue Cycle Simulation']
    : /robot|autonom|perception/i.test(context)
      ? ['Sensor Fusion Sandbox', 'Perception-to-Planning System', 'Autonomy Evaluation Lab']
      : /flight|space|aerospace|embedded/i.test(context)
        ? ['Flight Telemetry Decoder', 'Fault-Tolerant Command System', 'Mission Control Simulation']
        : [`${mission.projectSeeds[0]} Signal Explorer`, `${mission.projectSeeds[1]} Operating System`, `${mission.projectSeeds[2]} Evaluation Lab`]
  return [
    { id: 'foundation-role', project: 'Foundations', phase: 'Foundations', kind: 'reading', title: `Map the ${role} evidence`, summary: 'Translate the target into a short, honest evidence checklist.', resources: resources.slice(0, 2), actions: ['Read the linked primary documentation.', 'Write the three strongest role requirements.', 'Mark which are already demonstrated and which need proof.'], proofAsk: 'Mark complete when you have reviewed the resources.', proofKinds: ['text'], checks: ['Reviewed the role evidence'], points: 15, completionMode: 'self', requirementIds: ['r1', 'r2', 'r3'] },
    { id: 'foundation-skill', project: 'Foundations', phase: 'Foundations', kind: 'lesson', title: `Prepare the ${lead} foundation`, summary: `Use a specific guide to establish the foundation the projects need.`, resources: resources.slice(1), actions: ['Work through the relevant sections.', 'Keep one small runnable example.', 'Write down one failure mode you now understand.'], proofAsk: 'Mark complete when the example runs.', proofKinds: ['text'], checks: ['Completed the exact resource'], points: 15, completionMode: 'self', requirementIds: ['r1'] },
    { id: 'project-1', project: 'Build', phase: 'Build', projectId: 'project-1', kind: 'project', title: names[0], summary: `Create a focused first build using ${lead}, realistic data, and explicit quality checks.`, resources, actions: ['Define the input and output contract.', 'Implement the smallest end-to-end path.', 'Add tests for three malformed or missing inputs.'], proofAsk: 'Submit the public repository or artifact link.', proofKinds: ['link'], checks: ['Runs from a clean setup', 'Includes at least three edge cases', 'README shows sample output and maps it to the role'], minCommits: 5, points: 40, completionMode: 'evidence', requirementIds: ['r1'] },
    { id: 'expert-feedback', project: 'Learn from practitioners', phase: 'Expert feedback', kind: 'networking', title: `Ask a ${role} to challenge your first build`, summary: 'Use a concrete artifact to start a useful conversation and turn practitioner feedback into a design decision.', resources: [], actions: [`Find a ${role} or domain practitioner through your university alumni directory, a relevant professional community, or a sourced company profile.`, `Share the README or 90-second walkthrough of ${names[0]} and name the assumption you are least sure about.`, 'Ask: “Which failure case would make this least credible in real work, and what would you test next?”', 'Record the answer, decide what to change, and send a short follow-up showing what you incorporated.'], proofAsk: 'Submit an anonymized outreach message, the feedback received, and the exact change you will make (100+ words total).', proofKinds: ['text', 'file'], checks: ['Outreach shares a useful artifact instead of asking generically for time', 'Question is specific to a project decision', 'Response or attempted outreach is documented', 'Names a concrete change or a reasoned decision not to change'], points: 35, completionMode: 'evidence', requirementIds: ['r2', 'r3'] },
    { id: 'project-2', project: 'Scale', phase: 'Scale', projectId: 'project-2', kind: 'project', title: names[1], summary: 'Design the deeper system: state, interfaces, failures, observability, and tradeoffs.', resources, actions: ['Draw the system boundary and data flow.', 'Implement the core service and failure handling.', 'Add observable metrics and a repeatable test harness.'], proofAsk: 'Submit the repository and architecture note.', proofKinds: ['link'], checks: ['Documents interfaces and failure states', 'Includes repeatable integration tests', 'Reports at least two operational metrics'], minCommits: 8, points: 50, completionMode: 'evidence', requirementIds: ['r1', 'r2'] },
    { id: 'project-3', project: 'Scale', phase: 'Scale', projectId: 'project-3', kind: 'project', title: names[2], summary: 'Turn the work into an ambitious, reproducible evaluation with measurable results.', resources, actions: ['Generate a scenario suite with normal and adversarial cases.', 'Compare at least two approaches or configurations.', 'Publish results, limitations, and a concise demo.'], proofAsk: 'Submit artifact links and the acceptance report.', proofKinds: ['link', 'text'], checks: ['Uses reproducible scenarios', 'Compares explicit metrics', 'Explains limitations and maps evidence to all requirements'], minCommits: 10, points: 60, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] },
    { id: 'plan-review', project: 'Review and adapt', phase: 'Review', kind: 'reflection', title: 'Choose the strongest evidence and revise the plan', summary: 'Use what you learned from the builds and outside feedback to decide what deserves another iteration.', resources: [], actions: ['Compare each artifact against the target requirements.', 'Name the strongest signal and the weakest unsupported claim.', 'Choose one project to deepen, replace, or stop and explain why.', 'Write the next measurable experiment based on your evidence.'], proofAsk: 'Submit your evidence review and revised next move (150+ words).', proofKinds: ['text'], checks: ['References concrete project evidence', 'Identifies a real weakness or unsupported claim', 'Makes a reasoned keep, change, or stop decision', 'Defines a measurable next experiment'], points: 30, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] },
    { id: 'interview-story', project: 'Interview / Application', phase: 'Interview / Application', kind: 'interview', title: 'Defend the flagship in an interview', summary: 'Turn the technical evidence into a clear problem, decision, result, and limitation story.', resources: [], actions: ['Explain the problem without company jargon.', 'Defend one tradeoff and an alternative you rejected.', 'State a result, limitation, and next experiment.'], proofAsk: 'Write your interview answer (120+ words).', proofKinds: ['text'], checks: ['Explains a concrete decision', 'Uses measured evidence', 'Names a limitation without hand-waving'], points: 25, completionMode: 'evidence', requirementIds: ['r2', 'r3'] },
  ]
}

type NeighborTrack = {
  craft: string
  fundamentals: string
  tools: string
  focusedBuild: string
  systemBuild: string
  flagship: string
  metric: string
  practitioner: string
  resources: { foundation: LearningResource[]; tools: LearningResource[]; systems: LearningResource[] }
  toolBuild: string[]
  focusedActions: string[]
  systemActions: string[]
  flagshipActions: string[]
}

const course = (title: string, provider: string, url: string, skill: string, kind: LearningResource['kind'] = 'exercise'): LearningResource => ({ title, provider, url, skill, kind })

const sharedSql = course('CS50’s Introduction to Databases with SQL', 'Harvard OpenCourseWare', 'https://cs50.harvard.edu/sql/', 'Relational data modeling and SQL')
const productCourse = course('Digital Product Management: Modern Fundamentals', 'University of Virginia · Coursera', 'https://www.coursera.org/learn/uva-darden-digital-product-management', 'Product discovery and experiments', 'video')
const designCourse = course('Google UX Design Professional Certificate', 'Google · Coursera', 'https://www.coursera.org/professional-certificates/google-ux-design', 'Research, prototyping, and usability testing', 'video')
const figmaCourse = course('Create High-Fidelity Designs and Prototypes in Figma', 'Google · Coursera', 'https://www.coursera.org/learn/high-fidelity-designs-prototype', 'Figma prototypes and design handoff', 'exercise')
const systemDesignVideo = course('System Design for Beginners Course', 'freeCodeCamp.org · YouTube', 'https://www.youtube.com/watch?v=m8Icp_Cid5o', 'Scalable system design', 'video')

const neighborTrackFor = (role: string): NeighborTrack => {
  if (/data|analyst|science|machine learning|\bai\b/i.test(role)) return {
    craft: 'marketplace data', fundamentals: 'SQL, statistics, and experiment design', tools: 'SQL, Python, dbt, and a BI layer',
    focusedBuild: 'Marketplace Liquidity Diagnostic', systemBuild: 'Trust & Safety Signal Pipeline', flagship: 'Space Utilization Forecasting System',
    metric: 'coverage, precision, calibration, and decision lift', practitioner: 'data engineer, analyst, or trust-and-safety operator',
    resources: {
      foundation: [sharedSql, course('Intro to SQL', 'Kaggle Learn', 'https://www.kaggle.com/learn/intro-to-sql', 'SQL analysis'), course('Intro to Machine Learning', 'Kaggle Learn', 'https://www.kaggle.com/learn/intro-to-machine-learning', 'Model validation')],
      tools: [course('Pandas', 'Kaggle Learn', 'https://www.kaggle.com/learn/pandas', 'Data cleaning and analysis'), course('Data Visualization', 'Kaggle Learn', 'https://www.kaggle.com/learn/data-visualization', 'Explanatory visualization')],
      systems: [course('Intermediate Machine Learning', 'Kaggle Learn', 'https://www.kaggle.com/learn/intermediate-machine-learning', 'Leakage, missing data, and pipelines'), systemDesignVideo],
    },
    toolBuild: ['Create a reproducible generator for 10,000 synthetic listings, searches, booking requests, cancellations, reviews, and disputes.', 'Define listing_id, host_id, renter_id, ZIP code, space type, monthly price, distance, created_at, booked_at, cancellation_reason, and review_score.', 'Write SQL for search-to-request conversion, request-to-book conversion, median days-to-book, utilization, repeat booking, and cancellation rate.', 'Publish a data dictionary, five tested queries, and one decision memo.'],
    focusedActions: ['Generate 25 ZIP codes with deliberately uneven supply and demand.', 'Compute supply-to-demand ratio, median search radius, time-to-first-booking, and unfulfilled-search rate by ZIP and space type.', 'Build an interactive liquidity map that flags cold-start, supply-constrained, and demand-constrained markets.', 'Validate every metric against hand-calculated fixtures and document sparse-data, duplicate-event, and outlier failures.'],
    systemActions: ['Build an event pipeline for listing_created, identity_verified, booking_requested, payment_failed, booking_cancelled, review_submitted, and dispute_opened.', 'Engineer transparent risk features without protected attributes: account age, verification state, message velocity, price deviation, cancellation history, and review history.', 'Compare a rules baseline with logistic regression; publish precision/recall, calibration, false-positive slices, and an operator review queue.', 'Add drift, missing-field, late-event, duplicate-event, and threshold regression tests.'],
    flagshipActions: ['Simulate 52 weeks of hosts, renters, listings, searches, bookings, cancellations, and seasonality across 25 ZIP codes.', 'Forecast unmet demand and expected utilization by ZIP and space type with a naive baseline plus one stronger model.', 'Recommend where to recruit hosts and quantify expected incremental matched bookings with confidence intervals.', 'Backtest on held-out weeks, run price-shock and supply-shock scenarios, and publish model limitations and a three-minute decision walkthrough.'],
  }
  if (/product manager|growth|marketing|operations|sales/i.test(role)) return {
    craft: 'marketplace product strategy', fundamentals: 'marketplace economics, customer discovery, and experiment design', tools: 'SQL, product analytics, prototyping, and concise product writing',
    focusedBuild: 'Host Liquidity Opportunity Memo', systemBuild: 'Trust-First Booking Experiment', flagship: 'Neighborhood Supply Growth Playbook',
    metric: 'activation, match rate, conversion, and retention', practitioner: 'product, growth, host-success, or marketplace operator',
    resources: { foundation: [productCourse, sharedSql], tools: [course('Google Data Analytics Professional Certificate', 'Google · Coursera', 'https://www.coursera.org/professional-certificates/google-data-analytics', 'Funnels and evidence-based decisions', 'video')], systems: [productCourse, systemDesignVideo] },
    toolBuild: ['Create a synthetic host-and-renter funnel dataset covering listing start, listing publish, search, detail view, booking request, approval, payment, and repeat booking.', 'Write a KPI tree for available supply, qualified demand, match rate, booking conversion, time-to-book, utilization, cancellation, and 90-day repeat rate.', 'Build a spreadsheet or SQL funnel that reconciles every stage to a fixed cohort.', 'Publish a weekly marketplace review memo with one recommendation and one explicit non-recommendation.'],
    focusedActions: ['Interview five people who have rented storage or have unused garage, driveway, basement, or shed space.', 'Create a ZIP-level opportunity model using synthetic supply/demand plus public Census household and housing indicators.', 'Write a six-page Host Liquidity Opportunity Memo naming the target segment, unmet need, current workaround, KPI tree, risks, and smallest concierge test.', 'Prototype the host acquisition message and test comprehension and willingness with five participants.'],
    systemActions: ['Specify a trust-first booking experiment that exposes verification, host response history, cancellation terms, and review evidence at the decision point.', 'Write event names, properties, eligibility rules, guardrails, sample-size assumptions, and stopping criteria.', 'Create clickable renter and host flows plus an experiment readout template populated with synthetic outcomes.', 'Run a pre-mortem covering adverse selection, false reassurance, discrimination risk, and metric gaming.'],
    flagshipActions: ['Select three adjacent ZIP codes and build a 12-week supply launch plan for one space type.', 'Model the loop from host acquisition to searchable supply to renter match to review-generated trust to repeat demand.', 'Create channel experiments, a weekly operating dashboard, owner-level playbooks, and stop/scale thresholds.', 'Run base, weak-demand, low-trust, and host-churn scenarios; publish a board-style readout and a three-minute pitch.'],
  }
  if (/design|ux|research/i.test(role)) return {
    craft: 'marketplace experience design', fundamentals: 'interaction design, research, accessibility, and experimentation', tools: 'Figma, moderated research, prototyping, and analytics',
    focusedBuild: 'Storage Search Usability Study', systemBuild: 'Trust-First Booking Prototype', flagship: 'End-to-End Host and Renter Experience',
    metric: 'task success, time on task, confidence, and conversion intent', practitioner: 'product designer, researcher, host-success, or trust-and-safety operator',
    resources: { foundation: [designCourse, course('Principles of UX/UI Design', 'Meta · Coursera', 'https://www.coursera.org/learn/principles-of-ux-ui-design/', 'Research and interaction design', 'video')], tools: [figmaCourse, course('Evaluating Designs with Users', 'University of Michigan · Coursera', 'https://www.coursera.org/learn/evaluating-designs-with-users', 'Usability testing')], systems: [figmaCourse, productCourse] },
    toolBuild: ['Create a Figma library for listing cards, price units, distance, dimensions, amenities, verification, reviews, cancellation, availability, and booking states.', 'Design responsive renter search and host listing flows at mobile and desktop widths.', 'Define empty, loading, validation, unavailable, payment-failed, cancelled, and dispute states.', 'Run an accessibility pass for keyboard order, labels, contrast, error recovery, and 200% zoom.'],
    focusedActions: ['Recruit five people who have searched for storage, moved, or considered renting out extra space.', 'Give them one task: find a suitable 10×10-equivalent space within five miles and decide whether they trust the listing enough to request it.', 'Test a realistic prototype containing price, distance, dimensions, access hours, photos, verification, reviews, and cancellation terms.', 'Report task success, time on task, confidence, top breakdowns, and a revised search/listing flow.'],
    systemActions: ['Design both sides of booking: renter request, host approval, identity verification, payment, access coordination, cancellation, review, and dispute.', 'Create a state diagram and clickable prototype for every normal and recovery state.', 'Test three trust treatments with eight participants and record comprehension, confidence, and conversion intent.', 'Publish a design rationale showing which treatment won, what failed, and what engineering would need to build.'],
    flagshipActions: ['Design the end-to-end journey from host onboarding and listing creation through renter search, booking, access, recurring payment, review, and rebooking.', 'Build a reusable Figma component library and interactive prototype for mobile and desktop.', 'Run two moderated rounds with at least five participants each, including one accessibility-focused session.', 'Publish research clips or anonymized notes, metrics, before/after flows, design tokens, handoff annotations, and a three-minute case study.'],
  }
  return {
    craft: 'marketplace software engineering', fundamentals: 'programming, data structures, APIs, databases, and testing', tools: 'TypeScript, React, backend APIs, SQL, Git, and cloud deployment',
    focusedBuild: 'Marketplace Liquidity Explorer', systemBuild: 'Trust-Aware Booking Service', flagship: 'Unused-Space Marketplace Simulator',
    metric: 'correctness, latency, reliability, and marketplace match rate', practitioner: 'software engineer, product engineer, or marketplace operator',
    resources: {
      foundation: [course('Full Stack open', 'University of Helsinki', 'https://fullstackopen.com/en/', 'React, TypeScript, APIs, and testing'), sharedSql],
      tools: [course('TypeScript in React — Full Tutorial', 'freeCodeCamp.org · YouTube', 'https://www.youtube.com/watch?v=aJP1AbZSqz8', 'Typed React components', 'video'), course('Full Stack open · Testing React apps', 'University of Helsinki', 'https://fullstackopen.com/en/part5/testing_react_apps', 'Component and end-to-end testing')],
      systems: [systemDesignVideo, course('Full Stack open · Relational databases', 'University of Helsinki', 'https://fullstackopen.com/en/part13', 'PostgreSQL and migrations')],
    },
    toolBuild: ['Define PostgreSQL tables for users, listings, availability, searches, booking_requests, bookings, reviews, and disputes, including constraints and indexes.', 'Seed 1,000 synthetic listings across 25 ZIP codes with space type, dimensions, price, amenities, verification, and coordinates.', 'Build a typed React search results page backed by a REST API with filters for ZIP/radius, price, size, space type, and availability.', 'Add unit, API, and browser tests plus a README containing the ERD and p95 search latency.'],
    focusedActions: ['Build a Map/List liquidity explorer over 1,000 synthetic Neighbor-style listings and 5,000 synthetic searches.', 'Implement radius, price, size, space-type, availability, and verified-host filters with shareable query parameters.', 'Show results count, median price, estimated drive distance, and low-supply warnings by ZIP.', 'Test empty results, malformed coordinates, unavailable inventory, duplicate listings, and mobile keyboard navigation; report p95 response time.'],
    systemActions: ['Implement booking states requested, approved, payment_pending, confirmed, active, cancelled, completed, and disputed as an explicit state machine.', 'Add idempotency keys, overlapping-date protection, authorization rules, audit events, and a fake payment adapter with deterministic failures.', 'Expose host approve/decline and renter cancel flows in a minimal UI; emit metrics for approval time, failed transitions, and cancellation rate.', 'Prove behavior with concurrent-booking, duplicate-request, payment-failure, unauthorized-transition, and retry tests.'],
    flagshipActions: ['Simulate hosts creating listings and renters searching, requesting, booking, cancelling, reviewing, and opening disputes across 25 ZIP codes.', 'Build a React client, TypeScript API, PostgreSQL store, background event worker, and operator console for failed bookings and disputes.', 'Add a matching score using distance, price fit, size fit, availability, and trust signals; compare it with distance-only ranking.', 'Load-test 10,000 listings and 100 concurrent searches, inject payment and worker failures, and publish latency, match-rate, recovery, architecture, and a three-minute demo.'],
  }
}

/** Neighbor follows a fixed 12-month curriculum; survey and resume evidence personalize its contents. */
export function buildNeighborPath(profile: StudentProfile, intake: ResumeIntake, mission: Mission, role: string, context?: { why?: string; motivation?: string }): PathStep[] {
  const track = neighborTrackFor(role)
  const skills = [...new Set([...profile.skills, ...intake.skills])].filter((skill) => !/computer science|^cs$|major/i.test(skill))
  const strengths = skills.slice(0, 3)
  const startingPoint = strengths.length ? strengths.join(', ') : profile.major || 'your current experience'
  const interests = profile.interests.slice(0, 2).join(' and ') || mission.themes.slice(0, 2).join(' and ')
  const personalReason = (context?.why || context?.motivation || `your interest in ${interests}`).replace(/[.!?]+$/, '')
  const gapNote = `Start from ${startingPoint}; test out of anything you can already demonstrate and spend the saved time deepening the build.`
  // Neighbor's preloaded steps carry their full brief directly; do not replace
  // them with the generic roadmap project cards generated for other companies.
  const common = (partial: Omit<PathStep, 'id'>, index: number): PathStep => ({ id: `neighbor-${index + 1}`, ...partial, projectId: undefined })
  return [
    common({ project: 'Month 1 · Foundations', phase: 'Foundations', kind: 'lesson', title: `Complete the ${role} foundation sprint`, summary: `Use the attached courses to close only the gaps in ${track.fundamentals}. ${gapNote}`, resources: track.resources.foundation, actions: [`Complete the exercises from the attached course that cover ${track.fundamentals}; skip sections you can prove with ${startingPoint}.`, 'Create a synthetic Neighbor dataset with 100 hosts, 250 storage listings, 500 renters, 2,000 searches, 300 booking requests, and 50 cancellations.', 'Write a one-page data dictionary and calculate listing activation, search-to-request conversion, request approval, booking conversion, utilization, and cancellation rate.', `Write three observations connecting the numbers to ${personalReason}.`], proofAsk: 'Submit the course exercise output, synthetic dataset, data dictionary, six metric calculations, and three observations.', proofKinds: ['link', 'file', 'text'], checks: ['Dataset contains all six required entities or events', 'All six metrics are reproducible', 'Course work targets an actual skill gap', 'Observations connect evidence to the user’s motivation'], points: 25, completionMode: 'evidence', requirementIds: ['r1'] }, 0),
    common({ project: 'Months 1–2 · Role tools', phase: 'Role tools', kind: 'project', title: `Build the Neighbor marketplace workbench`, summary: `Use ${track.tools} to turn one fixed synthetic marketplace into a reviewer-ready working artifact.`, resources: track.resources.tools, actions: track.toolBuild, proofAsk: 'Submit the public workbench, source files, setup instructions, sample output, and test or reconciliation results.', proofKinds: ['link', 'file'], checks: ['Uses the specified Neighbor marketplace entities', 'Produces all required outputs', 'Can be reproduced from source', 'Includes tests or reconciliations and a decision memo'], minCommits: 5, points: 40, completionMode: 'evidence', requirementIds: ['r1'] }, 1),
    common({ project: 'Months 2–3 · Marketplace mechanics', phase: 'Domain', kind: 'reading', title: 'Model how Neighbor’s marketplace works', summary: `Learn the mechanics behind unused-space supply, renter demand, liquidity, trust, and local density through the lens of ${track.craft}.`, resources: [], actions: ['Map the host and renter journey from listing to completed storage.', 'Define supply, demand, liquidity, trust, and utilization in measurable terms.', `Identify where a ${role} can change one of those measures.`, `Use your stated reason—${personalReason}—to choose which marketplace constraint deserves attention.`], proofAsk: 'Submit a one-page marketplace model with assumptions, metrics, and the intervention you would test.', proofKinds: ['text', 'file', 'link'], checks: ['Models both host and renter sides', 'Defines at least three measurable marketplace signals', 'Names assumptions instead of presenting them as company facts'], points: 30, completionMode: 'evidence', requirementIds: ['r1', 'r2'] }, 2),
    common({ project: 'Months 3–4 · Focused build', phase: 'Build', kind: 'project', projectId: 'project-1', title: `Build ${track.focusedBuild}`, summary: `Ship a complete first Neighbor project using ${startingPoint}, not a generic portfolio exercise.`, resources: track.resources.tools, actions: track.focusedActions, proofAsk: 'Submit the working artifact, source, sample data, metric definitions, test evidence, failure log, README, and a 90-second walkthrough.', proofKinds: ['link', 'file'], checks: ['Implements every specified input and output', 'Reports the named marketplace metrics', 'Tests the specified failure cases', 'Explains one decision Neighbor could make from the result'], minCommits: 8, points: 55, completionMode: 'evidence', requirementIds: ['r1', 'r2'] }, 3),
    common({ project: 'Months 4–5 · Feedback loop', phase: 'Feedback', kind: 'networking', title: 'Put the first build in front of a practitioner', summary: 'Use the artifact to earn specific criticism, then change the work.', resources: [], actions: [`Find a ${track.practitioner} through BYU, a Utah product community, or Neighbor’s public team network.`, `Share ${track.focusedBuild} and the assumption you trust least.`, 'Ask: “Which failure case or marketplace constraint would make this least credible in real work?”', 'Implement or explicitly reject the feedback and document why.'], proofAsk: 'Submit the outreach, anonymized feedback, and before/after evidence of the decision it changed.', proofKinds: ['text', 'file', 'link'], checks: ['Leads with a useful artifact', 'Asks a role-specific question', 'Documents the response or a thoughtful outreach attempt', 'Shows the resulting decision'], points: 35, completionMode: 'evidence', requirementIds: ['r2', 'r3'] }, 4),
    common({ project: 'Months 5–6 · Systems build', phase: 'Systems', kind: 'project', projectId: 'project-2', title: `Build ${track.systemBuild}`, summary: 'Build the exact trust and booking system below, including recovery paths and operational evidence.', resources: track.resources.systems, actions: track.systemActions, proofAsk: 'Submit the artifact, architecture or experiment spec, source material, test plan, measured results, and failure analysis.', proofKinds: ['link', 'file'], checks: ['Implements every specified state or analytical stage', 'Measures trust and marketplace outcomes', 'Exercises the required failure and abuse cases', 'Publishes repeatable tests or a reproducible experiment readout'], minCommits: 10, points: 60, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] }, 5),
    common({ project: 'Months 6–7 · Role depth', phase: 'Specialization', kind: 'lesson', title: `Improve ${track.systemBuild} against a baseline`, summary: `Use the attached advanced course, then prove one technique improves ${track.metric}.`, resources: track.resources.systems, actions: ['Choose the weakest measured result from the systems build as the baseline.', `Complete the attached lesson most relevant to that weakness in ${track.craft}.`, 'Implement one improvement without changing the evaluation dataset or task.', `Compare before and after on ${track.metric}, runtime or effort, and at least one negative side effect.`, 'Write a two-page decision record: context, options, evidence, decision, consequences, and rollback trigger.'], proofAsk: 'Submit the baseline, revised artifact, controlled comparison, and two-page decision record.', proofKinds: ['text', 'link', 'file'], checks: ['Uses the same evaluation conditions before and after', 'Reports a positive and negative result', 'Links the course concept to the implementation', 'Defines a rollback trigger'], points: 40, completionMode: 'evidence', requirementIds: ['r1', 'r2'] }, 6),
    common({ project: 'Months 7–9 · Flagship', phase: 'Flagship', kind: 'project', projectId: 'project-3', title: `Build ${track.flagship}`, summary: `Create the complete Neighbor portfolio centerpiece with a two-sided marketplace, measured outcomes, injected failures, and a shipped revision.`, resources: track.resources.systems, actions: track.flagshipActions, proofAsk: 'Submit the deployed or reviewable flagship, source, synthetic-data generator, architecture, test/evaluation report, failure injection results, revision history, and three-minute demo.', proofKinds: ['link', 'file'], checks: ['Covers host, renter, and operator needs', 'Reports reproducible marketplace and quality metrics', 'Includes injected failure or adverse scenarios', 'Shows a revision driven by measured evidence', 'Can be reviewed without private Neighbor data'], minCommits: 15, points: 70, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] }, 7),
    common({ project: 'Months 9–10 · Systems thinking', phase: 'Systems thinking', kind: 'reflection', title: 'Run a failure-mode review', summary: 'Show that you can reason about a marketplace as a system, not just ship an isolated artifact.', resources: [], actions: ['List failure modes across people, process, data, technology, and marketplace incentives.', 'Score likelihood, severity, detectability, and mitigation.', 'Trace one failure across host, renter, Neighbor, and community effects.', 'Choose one mitigation and validate it in the flagship.'], proofAsk: 'Submit the failure-mode analysis and proof of one tested mitigation.', proofKinds: ['file', 'text', 'link'], checks: ['Covers technical and human failure modes', 'Uses an explicit prioritization method', 'Tests one mitigation', 'States residual risk honestly'], points: 40, completionMode: 'evidence', requirementIds: ['r2', 'r3'] }, 8),
    common({ project: 'Months 10–11 · Portfolio', phase: 'Portfolio', kind: 'project', title: `Package the evidence for a ${role} reviewer`, summary: 'Make the work easy to inspect: decisions, calculations or analysis, artifact, failures, data, and changes.', resources: [], actions: ['Select the strongest three to five artifacts instead of publishing everything.', 'Write each case study as problem, decision, evidence, result, failure, and revision.', 'Put setup, demo, and results links at the top.', `Map every claim to the ${role} requirements and remove unsupported claims.`], proofAsk: 'Submit the public portfolio or repository index and the requirement-to-evidence map.', proofKinds: ['link', 'file'], checks: ['Contains three to five serious artifacts', 'Makes results and limitations easy to find', 'Maps claims to inspectable evidence', 'Uses clear language rather than course-completion claims'], points: 45, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] }, 9),
    common({ project: 'Months 10–12 · Interview readiness', phase: 'Interview', kind: 'interview', title: `Defend the work as a ${role}`, summary: 'Practice the questions the portfolio creates and prove you understand every decision.', resources: [], actions: ['Prepare a two-minute flagship walkthrough.', 'Defend one tradeoff, one failure, one measured result, and one next experiment.', 'Complete a role-specific work sample or mock interview.', 'Revise the weakest answer using recorded feedback.'], proofAsk: 'Submit the recorded or written mock interview, feedback, and revised answer.', proofKinds: ['file', 'link', 'text'], checks: ['Explains a concrete decision', 'Uses measured evidence', 'Names a limitation without hand-waving', 'Shows improvement after feedback'], points: 40, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] }, 10),
    common({ project: 'Month 12 · Application campaign', phase: 'Application', kind: 'networking', title: 'Run a focused Neighbor application campaign', summary: 'Turn twelve months of evidence into thoughtful conversations and a role-specific application.', resources: [], actions: ['Identify relevant Neighbor roles and adjacent Utah marketplace teams without inventing openings.', `Ask practitioners to critique one ${role} artifact, not to “pick their brain.”`, 'Tailor the resume around verified outcomes and the target role.', 'Send a concise application package with the flagship demo and evidence map.', 'Track responses, questions, and the next iteration each week.'], proofAsk: 'Submit the tailored resume, outreach sample, application package, and a private tracking summary.', proofKinds: ['file', 'text', 'link'], checks: ['Targets a specific role', 'Leads with relevant evidence', 'Uses honest, measured claims', 'Includes a follow-up and iteration loop'], points: 50, completionMode: 'evidence', requirementIds: ['r1', 'r2', 'r3'] }, 11),
  ]
}
